apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: flask-monitor
  namespace: default
  labels:
    release: prometheus

spec:
  selector:
    matchLabels:
      app: flask-app

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
